apiVersion: v1
kind: Template
metadata:
  name: elasticsearch
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      ports:
        - name: 9200-tcp
          port: 9200
          protocol: TCP
          targetPort: 9200
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      ports:
        - name: 9300-tcp
          port: 9300
          protocol: TCP
          targetPort: 9300
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      port:
        targetPort: 9200-tcp
      to:
        kind: Service
        name: ${APP_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}-transport
      name: ${APP_NAME}-transport
    spec:
      port:
        targetPort: 9300-tcp
      to:
        kind: Service
        name: ${APP_NAME}

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: ${IMAGE}
          from:
            kind: DockerImage
            name: ${IMAGE}
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - image: ${IMAGE}
              imagePullPolicy: Always
              name: ${APP_NAME}
              ports:
                - containerPort: 8888
                  protocol: TCP
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:latest
              namespace: ${PROJECT_NAME}
          type: ImageChange

parameters:
- name: PROJECT_NAME
  required: true
- name: APP_NAME
  required: true
  value: elasticsearch
- name: IMAGE
  required: true
  value: humair88/elasticsearch

