apiVersion: v1
kind: Template
metadata:
  name: logstash
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      ports:
        - name: 5044-tcp
          port: 5044
          protocol: TCP
          targetPort: 5044
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}-monitoring
      name: ${APP_NAME}-monitoring
    spec:
      ports:
        - name: 9600-tcp
          port: 9600
          protocol: TCP
          targetPort: 9600
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      port:
        targetPort: 5044-tcp
      to:
        kind: Service
        name: ${APP_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}-monitoring
      name: ${APP_NAME}-monitoring
    spec:
      port:
        targetPort: 9600-tcp
      to:
        kind: Service
        name: ${APP_NAME}-monitoring

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: ${IMAGE}
          from:
            kind: DockerImage
            name: ${IMAGE}
          name: latest
          referencePolicy:
            type: Source

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - image: ${IMAGE}
              imagePullPolicy: Always
              name: ${APP_NAME}
              volumeMounts:
              - name: app-config
                mountPath: /usr/share/logstash/config/
          volumes:
            - name: app-config
              configMap:
                name: example-logstash-config
                items:
                - key: logstash-config
                  path: logstash.conf
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:latest
          type: ImageChange

parameters:
- name: APP_NAME
  required: true
  value: logstash
- name: IMAGE
  required: true
  value: humair88/logstash